124 マップの変更操作
nitfc-festival-system-team/2023hp pull request #144
Opened 2023-10-25 08:55 UTC by LITl-l

Closes #<issue No.>

### 変更内容
- マップの差し替え
- 露店の場所をクリック時に各露店の詳細に遷移
- 遷移時に対象を明滅するアニメーション

iPad未確認
アニメーションは暫定

2023-10-25 12:42 UTC, void2610 requested changes
🙂

2023-10-25 12:42 UTC, void2610 commented on src/features/checkIsMobile.ts
featuresじゃなくてhooksディレクトリに置いて欲しい

2023-10-26 00:01 UTC, LITl-l commented on src/features/checkIsMobile.ts
直しや下

2023-10-26 00:06 UTC, void2610 approved these changes
💅🏻

2023-10-26 00:06 UTC, merged