34-露店一覧ページを作る
nitfc-festival-system-team/2023hp pull request #47
Opened 2023-10-09 17:10 UTC by suisosuii

見た目ほぼお知らせからパクってページ遷移機能つけただけ

Closes #<issue No.>

### 変更内容
-

### 次回以降の PR でやるべきこと
-

2023-10-09 17:14 UTC, LITl-l requested changes
ページいっぱい使えばいいと思う

2023-10-10 09:44 UTC, void2610 requested changes
リンクマーク？みたいなののボタンつけてボタン押すとページ遷移がいいかも
ボタンになってることが分かりにくい

2023-10-10 14:44 UTC, LITl-l commented on src/components/Stand.tsx
> +  margin: 0.5em 0.5em;
このマージンを残すならstandListか各スタンドにもマージンをつけて、要素の左側を揃えた方がいいかも
![image](https://github.com/nitfc-festival-system-team/2023hp/assets/52400018/fd800c3c-73d6-4e20-830e-58347de78c0a)

2023-10-10 15:02 UTC, void2610 commented
リンクボタンはめっちゃ想像通りのやつでナイス
だだボタンとして独立させてボタン以外押しても飛ばないようにしてもいいかも

2023-10-10 15:02 UTC, void2610 approved these changes

2023-10-10 15:07 UTC, void2610 commented
リンクマークをもう少し文字から離して、青色（リンクの色）にしたら分かりやすいと思う

2023-10-10 17:34 UTC, LITl-l approved these changes
☕

2023-10-10 17:37 UTC, merged